### ISSUE TITLE
Distributed PPO with L-BFGS algorithm

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [deeplearninc/relaax#12]
TODO: Distributed version of PPO - Proximal Policy Optimization (i.e., TRPO, but using a penalty instead of a constraint on KL divergence), where each subproblem is solved with L-BFGS

**Comment by 4SkyNet** [comment]
**Merged** to `v2` branch with `trpo`:
[93261ef3433a95573308526ee27c9de4cea23a75](https://github.com/deeplearninc/relaax/tree/93261ef3433a95573308526ee27c9de4cea23a75)
