### ISSUE TITLE
Choose action_size for DeepMind Lab environment

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [deeplearninc/relaax#13]
I've added action_size parameter to current implementation for now.
You can choose between 3 predefined cases:

s or smal to set small action_size
m or medium to set medium action_size (movement only)
f or full (b or big) to set full action_size
[updated readme](https://github.com/deeplearninc/relaax/tree/add_action_size_to_lab#deepmind-lab)

See add_action_size_to_lab branch for details [#21](https://github.com/deeplearninc/relaax_old/pull/21)

P.S> docker is also updated & uploaded

**Comment by 4SkyNet** [comment]
These changes is already Merged to `v1` by https://github.com/deeplearninc/relaax/commit/10d78fec45b9a7465826c82e3e7a1e9a1016e445
