### ISSUE TITLE
Distributed TRPO-GAE algorithm

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [deeplearninc/relaax#3]
TODO: Distributed version of TRPO-GAE algorithm ([original paper](https://arxiv.org/pdf/1506.02438.pdf))
See trpo_gae branch for details [#7](https://github.com/deeplearninc/relaax_old/pull/7)

**Comment by 4SkyNet** [comment]
gym's bipedal-walker can walks after several updates and stabilize at 200k steps for a bit long time
![bipedal-walker-trpo](https://cloud.githubusercontent.com/assets/8963763/22500771/5ecb2c90-e87f-11e6-9845-94b924267e81.png)

**Comment by 4SkyNet** [comment]
One more run (I've changed filter creation a bit, but it shouldn't matter)
This improvements is made by experience batch size: it increased from 10k to 20k
![bipedal-walker-trpo-fixed](https://cloud.githubusercontent.com/assets/8963763/22563558/78b96b28-e99a-11e6-9aa4-17700e5ab0c3.png)

**Comment by 4SkyNet** [comment]
One more (control) run with 10k:
![bipedal-walker-trpo-10k-control](https://cloud.githubusercontent.com/assets/8963763/22585023/141aaaae-ea0f-11e6-932b-6c60177e0a08.png)

**Comment by 4SkyNet** [comment]
async version: straightforward non-blocking collecting isn't good as expected (batch 12k, 8 clients)
![bipedal-walker-trpo-async-12k](https://cloud.githubusercontent.com/assets/8963763/22819858/8ecbf568-ef8d-11e6-8cb9-d499201a4e3e.png)

**Comment by 4SkyNet** [comment]
The new look of `updated trpo` with the same 10k batch  & 1.6 trajectory (with `filter`)
![bipedal-walker-upd-trpo-10k](https://cloud.githubusercontent.com/assets/8963763/23549873/9f8f67cc-0027-11e7-8660-0136c77a0f96.png)

**Comment by 4SkyNet** [comment]
`Non-blocking` trpo (while update) with 10k batch & 1.6 trajectory (with `filter`)
![trpo_non-blocking_10k](https://cloud.githubusercontent.com/assets/8963763/24068796/f21ebd08-0ba8-11e7-97a5-2ce359e13c1f.png)

**Comment by 4SkyNet** [comment]
`Non-blocking` trpo without `filter` with 10k batch & 1.6 trajectory
![trpo_non-blocking_non-filter_10k](https://cloud.githubusercontent.com/assets/8963763/24068813/5af76f00-0ba9-11e7-8e1a-6bd12b0502ed.png)

**Comment by 4SkyNet** [comment]
**Merged** to `v2` branch:
[93261ef3433a95573308526ee27c9de4cea23a75](https://github.com/deeplearninc/relaax/tree/93261ef3433a95573308526ee27c9de4cea23a75)

**Comment by 4SkyNet** [comment]
A bit `fixed` `Non-blocking` `trpo` without `filter` with 10k batch & 1.6 trajectory (last `v2`)
![last-v2-trpo](https://user-images.githubusercontent.com/8963763/27090876-1cd518a0-5067-11e7-9b1a-ee7b6a3d12f8.png)
