### ISSUE TITLE
Replace custom LSTM

### ISSUE THREAD

**Issue by StanislavVolodarskiy** [deeplearninc/relaax#8]
TODO: Replace custom `LSTM` with tensorflow `BasicLSTMCell`
(measure speedup if it could be)
See replace_lstm branch for details [#19](https://github.com/deeplearninc/relaax_old/pull/19)

**Comment by 4SkyNet** [comment]
Learning curve with tensorflow `BasicLSTMCell`: 8-agents, 120s-worker-timeout, gym-boxing
![da3c_tf-lstm_8ag_gym_boxing](https://cloud.githubusercontent.com/assets/8963763/24098310/e11af6e2-0d7a-11e7-92c7-0c32dd5eaa59.png)

**Comment by 4SkyNet** [comment]
Learning curve with current `CustomBasicLSTMCell`: 8-agents, 120s-worker-timeout, gym-boxing
![da3c_cur-lstm_8ag_gym_boxing](https://cloud.githubusercontent.com/assets/8963763/24274639/9f7aa1c0-103a-11e7-822d-1769c0321c76.png)

**Comment by 4SkyNet** [comment]
Manually `merged` by:
[81c0527c3f7c3d701834eaae2d3df27a8c39977a](https://github.com/deeplearninc/relaax/commit/81c0527c3f7c3d701834eaae2d3df27a8c39977a)
[1601cea15a3b2eeccede4cd21a09f25afcc3353e](https://github.com/deeplearninc/relaax/commit/1601cea15a3b2eeccede4cd21a09f25afcc3353e)
